<?php

declare(strict_types=1);

namespace Cresset\Magebuild;

// GENERATED by scripts/publish-composer-branch.sh — the magebuild binary
// version this Composer package installs. Always matches the package's git
// tag, so `composer require cresset/magebuild:0.1.0` fetches the
// magebuild-v0.1.0 binary.
const MAGEBUILD_VERSION = '0.1.0';
