<?php

declare(strict_types=1);

namespace Cresset\Magebuild;

// GENERATED by scripts/publish-composer-branch.sh — the magebuild binary
// version this Composer package installs. Always matches the package's git
// tag.
const MAGEBUILD_VERSION = '0.3.0';
